import type { AuditSummary } from "@/lib/audit-engine/types";

export type LeadInfo = {
  email: string;
  name?: string;
  auditId: string;
};

/**
 * Builds the HTML confirmation email sent to the person who submitted their email.
 * Uses only engine-provided figures — no invented numbers.
 */
export function buildConfirmationEmail(
  lead: LeadInfo,
  summary: AuditSummary
): { subject: string; html: string } {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://stackaudit.app";
  const resultsUrl = `${appUrl}/results/${lead.auditId}`;
  const greeting = lead.name ? `Hi ${lead.name},` : "Hi there,";
  const hasSavings = summary.totalAnnualSaving > 0;

  const savingsSection = hasSavings
    ? `<p style="font-size:16px;color:#111827;margin:0 0 12px;">
        Our audit found <strong style="color:#7c3aed;">$${summary.totalAnnualSaving.toFixed(0)} in potential annual savings</strong>
        across your ${summary.toolCount}-tool AI stack.
        That&rsquo;s ${summary.savingsPercent}% of your current spend of $${summary.totalMonthlySpend.toFixed(0)}/month.
      </p>
      <p style="font-size:15px;color:#374151;margin:0 0 20px;">
        We identified ${summary.recommendationCount} actionable recommendation${summary.recommendationCount !== 1 ? "s" : ""} to help you right-size your tools.
      </p>`
    : `<p style="font-size:16px;color:#111827;margin:0 0 20px;">
        Great news — your ${summary.toolCount}-tool AI stack is already well-optimised!
        No significant cost savings were identified at this time.
      </p>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Your StackAudit Results</title></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr><td style="background:linear-gradient(135deg,#7c3aed 0%,#5b21b6 100%);border-radius:12px 12px 0 0;padding:32px 40px;text-align:center;">
          <p style="margin:0;font-size:22px;font-weight:700;color:#ffffff;letter-spacing:-0.5px;">⚡ StackAudit</p>
          <p style="margin:8px 0 0;font-size:14px;color:#ddd6fe;">AI Spend Audit Report</p>
        </td></tr>

        <!-- Body -->
        <tr><td style="background:#ffffff;padding:40px;border-radius:0 0 12px 12px;border:1px solid #e5e7eb;border-top:none;">
          <p style="font-size:16px;color:#111827;margin:0 0 16px;">${greeting}</p>
          <p style="font-size:15px;color:#374151;margin:0 0 20px;">
            Thanks for running your AI stack audit. Here&rsquo;s a quick summary of what we found:
          </p>

          ${savingsSection}

          <!-- CTA -->
          <table cellpadding="0" cellspacing="0" style="margin:24px 0;">
            <tr><td style="background:#7c3aed;border-radius:8px;padding:12px 24px;">
              <a href="${resultsUrl}" style="color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">
                View Your Full Audit Report &rarr;
              </a>
            </td></tr>
          </table>

          <p style="font-size:13px;color:#6b7280;margin:24px 0 0;border-top:1px solid #f3f4f6;padding-top:20px;">
            This report was generated by StackAudit. All savings figures are based on publicly available pricing data and your reported spend — no numbers were invented.
          </p>
          <p style="font-size:12px;color:#9ca3af;margin:8px 0 0;">
            Audit ID: <code style="font-family:monospace;">${lead.auditId}</code>
          </p>
        </td></tr>

        <!-- Footer -->
        <tr><td style="padding:20px;text-align:center;">
          <p style="margin:0;font-size:12px;color:#9ca3af;">
            StackAudit &bull; AI Spend Optimization &bull;
            <a href="${appUrl}/audit" style="color:#7c3aed;text-decoration:none;">Run another audit</a>
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;

  return {
    subject: hasSavings
      ? `Your StackAudit found $${summary.totalAnnualSaving.toFixed(0)} in potential savings`
      : "Your StackAudit results are ready",
    html,
  };
}
